import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import Headers from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";

const outfit = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    < ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.className} font-sans bg-background text-foreground antialiased`}
        >
          <ConvexClientProvider>
            {children}

          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
